-- مرحله 1: تبدیل مقادیر غیرعددی به NULL
UPDATE dbo.[labour_force_all]
SET 
    F3_D02 = CASE WHEN TRY_CAST(F3_D02 AS INT) IS NULL AND F3_D02 IS NOT NULL THEN NULL ELSE F3_D02 END,
    F3_D03 = CASE WHEN TRY_CAST(F3_D03 AS INT) IS NULL AND F3_D03 IS NOT NULL THEN NULL ELSE F3_D03 END,
    F3_D04 = CASE WHEN TRY_CAST(F3_D04 AS INT) IS NULL AND F3_D04 IS NOT NULL THEN NULL ELSE F3_D04 END,
    F3_D05 = CASE WHEN TRY_CAST(F3_D05 AS INT) IS NULL AND F3_D05 IS NOT NULL THEN NULL ELSE F3_D05 END,
    F3_D06 = CASE WHEN TRY_CAST(F3_D06 AS INT) IS NULL AND F3_D06 IS NOT NULL THEN NULL ELSE F3_D06 END,
    F3_D49 = CASE WHEN TRY_CAST(F3_D47 AS INT) IS NULL AND F3_D47 IS NOT NULL THEN NULL ELSE F3_D47 END;  -- ✅ ویرگول اضافه شد
GO

-- مرحله 2: تغییر نوع داده به INT
ALTER TABLE dbo.[labour_force_all] ALTER COLUMN F3_D02 INT;
ALTER TABLE dbo.[labour_force_all] ALTER COLUMN F3_D03 INT;
ALTER TABLE dbo.[labour_force_all] ALTER COLUMN F3_D04 INT;
ALTER TABLE dbo.[labour_force_all] ALTER COLUMN F3_D05 INT;
ALTER TABLE dbo.[labour_force_all] ALTER COLUMN F3_D06 INT;
ALTER TABLE dbo.[labour_force_all] ALTER COLUMN F3_D47 INT;