-- ابتدا همه مقادیر غیرعددی را در ستون‌های مورد نظر به NULL تبدیل کن
UPDATE dbo.[labour_force_all]
SET 
    ActivityStatus = CASE WHEN TRY_CAST(ActivityStatus AS INT) IS NULL THEN NULL ELSE ActivityStatus END,
    F3_D49 = CASE WHEN TRY_CAST(F3_D49 AS INT) IS NULL THEN NULL ELSE F3_D49 END,
    F3_D02 = CASE WHEN TRY_CAST(F3_D02 AS INT) IS NULL THEN NULL ELSE F3_D02 END,
    F3_D03 = CASE WHEN TRY_CAST(F3_D03 AS INT) IS NULL THEN NULL ELSE F3_D03 END,
    F3_D04 = CASE WHEN TRY_CAST(F3_D04 AS INT) IS NULL THEN NULL ELSE F3_D04 END,
    F3_D05 = CASE WHEN TRY_CAST(F3_D05 AS INT) IS NULL THEN NULL ELSE F3_D05 END,
    F3_D06 = CASE WHEN TRY_CAST(F3_D06 AS INT) IS NULL THEN NULL ELSE F3_D06 END;
